---
title: "assisgment01"
author: "florencelei"
date: "2024-10-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 4 Create a data frame in R Markdown
```{r}
animals = c("Snake", "Ostrich", "Cat", "Spider")
num_legs = c(0, 2, 4, 8)
animals_df = data.frame(animals, num_legs)
animals_df
```

## 5 Matrix operations
```{r}
x_vect = seq(12,2,-2)
print(x_vect)

X = matrix(x_vect,nrow = 2,ncol = 3)
print(X)

Y = matrix(seq(4), 2, 2)
print(Y)

Z = matrix(c(4,6,8,10), 2, 2)
print(Z)

print(Y+Z)

print(Z+Y)

print(Y %*% X)

print(Y*Z)

print(Z*Y)

solve(Y)

print(Y%*%solve(Y))

print(solve(Y)%*%X)

solve(Y, X)
```

## 6 Writing a function with R
```{r}
myFirstRFunc = function(n){
  num = 0
  for (i in 1:(n-1)) {
    if(i%%2==0){
      num = num + i 
    }else if(i%%7==0){
      num = num + i
    }
  }
  return(num)
}
print(myFirstRFunc(1000))
```

## 7 Further R Markdown exercises
# Wave plot
```{r}
x = seq(0, 20, 0.01)
y = sin(x)
sin_df = data.frame(x,y)
head(sin_df,3)
plot(sin_df)
```

## insert mathematical formulae
$$
\sin^2(x)+\cos^2(x) = 1 
$$

$$
\sin(x)=\sum_{n=1}^{\infty}(-1)^{n+1}\cdot \frac{x^{2n-1}}{(2n-1)!}\approx x-\frac{x^3}{3!}+\frac{x^5}{5!}-\frac{x^7}{7!}\ldots. \]
$$

$$
A=\left(\begin{matrix} a_{11} & a_{12}\\ a_{21} & a_{22} \end{matrix}\right).
$$